/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'name-override': RouteRecordInfo<'name-override', '/', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    'who-me-override': RouteRecordInfo<'who-me-override', '/about/who/me', Record<never, never>, Record<never, never>>,
    '/deep/': RouteRecordInfo<'/deep/', '/deep', Record<never, never>, Record<never, never>>,
    '/deep/deeper/': RouteRecordInfo<'/deep/deeper/', '/deep/deeper', Record<never, never>, Record<never, never>>,
    '/deep/deeper/deepest/': RouteRecordInfo<'/deep/deeper/deepest/', '/deep/deeper/deepest', Record<never, never>, Record<never, never>>,
    '/module1': RouteRecordInfo<'/module1', '/module1', Record<never, never>, Record<never, never>>,
    '/module2': RouteRecordInfo<'/module2', '/module2', Record<never, never>, Record<never, never>>,
    '/news': RouteRecordInfo<'/news', '/news', Record<never, never>, Record<never, never>>,
    '/news/': RouteRecordInfo<'/news/', '/news', Record<never, never>, Record<never, never>>,
    'named-news-page': RouteRecordInfo<'named-news-page', '/news/Today', Record<never, never>, Record<never, never>>,
    '/nolayout': RouteRecordInfo<'/nolayout', '/nolayout', Record<never, never>, Record<never, never>>,
    '/second/': RouteRecordInfo<'/second/', '/second', Record<never, never>, Record<never, never>>,
    '/sublayout': RouteRecordInfo<'/sublayout', '/sublayout', Record<never, never>, Record<never, never>>,
  }
}
