packages:
  - examples/*
allowBuilds:
  cypress: true
  esbuild: true
  simple-git-hooks: true
  vue-demi: true
onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
